function isoList = readIsolatesTable(filename)
%
vars = ...
["iso","string";...
"species","string";...
"input_ref","string";...
"iso_fastq_path","string";...
"breseq_output_path","string";...
"experiment","string";...  
"iso_outpath","string";...
"ancestry_group","string";... 
"isfinder","logical";...
"genbank","logical";...
"sra","logical";...
"Name","string";...
"population","logical";...
"use","logical"]  ; 

opts = spreadsheetImportOptions(...
	"NumVariables",size(vars,1),...
	"VariableNames",vars(:,1)',...
	"VariableTypes",vars(:,2)',...
    "DataRange","A2",...
	"ImportErrorRule","fill");
opts = setvaropts(opts,'iso_outpath','FillValue',"myBreseq");
opts = setvaropts(opts,'experiment','FillValue',"unknown");
opts = setvaropts(opts,'isfinder','FillValue',false);
opts = setvaropts(opts,'sra','FillValue',true);
opts = setvaropts(opts,'genbank','FillValue',true);
opts = setvaropts(opts,'use','FillValue',true);
opts = setvaropts(opts,'ancestry_group','FillValue'," ");
opts = setvaropts(opts,'Name','FillValue'," ");

isoList = readtable(filename,opts) ; 
isoList = isoList(isoList.use,1:end-1) ; 
assert(length(unique(isoList.iso))==height(isoList)) % isolates names should be unique

end

